version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./docker/mongo/mongod.conf:/etc/mongod.conf:ro
      - mongo_data:/data/db
    ports:
      - 27017:27017
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: serverfarm_db
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  express:
    build: ./express
    depends_on:
      - mongodb
      - mysql
    ports: 
      - 5000:5000

volumes:
  mongo_data:
  mysql_data: